sudo: required
services:
    - docker

before_install:
    - docker build -t muhammadhasham2311/complex -f ./client/Dockerfile.dev ./client/

script:
    - docker run muhammadhasham2311/complex npm test -- --coverage

after_success:
    - docker build -t muhammadhasham2311/multi-client ./client
    - docker build -t muhammadhasham2311/multi-nginx ./nginx
    - docker build -t muhammadhasham2311/multi-server ./server
    - docker build -t muhammadhasham2311/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push muhammadhasham2311/multi-client
    - docker push muhammadhasham2311/multi-nginx
    - docker push muhammadhasham2311/multi-server
    - docker push muhammadhasham2311/multi-worker

deploy:
    provider: elasticbeanstalk
    reigon: us-east-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-493666602086
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY
